### ISSUE TITLE
Uninstall script 

### ISSUE THREAD

**Issue by kausky** [natask/gestures#7]
The Uninstall script when executed proceeds to remove almost everything including Firefox, shell and the system DE parts

**Comment by natask** [comment]
It prompts before removal does it not?
I made the uninstall script exhaustive (to the extent that packages aren't bulit-in) and optional to hand control to the user.
I believe it is the removal of one of these packages that prompts what you are referring to

python3
python3-pip
python-pip

looking over again

I may reduce it to only 
python3-pip
python-pip

because `python3` is basically built-in on most common distros.
and remove `git` from install/uninstall list as well because people installing would be using git already.

**Comment by kausky** [comment]
Hey, i am not sure which package does that because i was totally in a hurry, and yup you can totally remove git from the install and uninstall scripts because that is also pre packaged with the most common distros

**Comment by natask** [comment]
please confirm if you are getting the same issue on the latest master commit.

**Comment by kausky** [comment]
Hey, Just checked on Ubuntu 20.10 and with the latest master commit as of now that problem does not exist any more even after accepting to remove everything in `uninstall.sh`. 
Thank you ! 

Feel free to close the issue. I think it was mostly because of the removal of `python3`, A lot of the component do depend on it and has it as a dependency.
