### ISSUE TITLE
Could you clarify how to launch gestures please ?

### ISSUE THREAD

**Issue by prog-amateur2** [natask/gestures#8]
Hello, I am on Debian bullseye and I have installed gestures following the tutorial. 
After rebook I thought that it would work out of the box but I can't use any gesture. 
What is missing in my process ? Shall I open a terminal and launch something like "gestures" ? 
Maybe your answer can be added to the readme if it is short ?

Thank you for your clarification.

**Comment by natask** [comment]
It should work out the box. The application is launched at start up because of startup script https://github.com/natask/gestures/blob/ac649b487faca85ed2dfc1bdc61bb42b935c8369/install.sh#L96


can you check if the application runs in terminal.
do the following steps
- open terminal
- run command "gestures" without quotes

if gestures are not recognized
- run command "gestures debug" without quotes
check the line that reads, "Handlers for touchpads:" and see if a touchpad has been detected. I imagine that to be the reason why it is not working.

**Comment by prog-amateur2** [comment]
Hello, sorry for my late reply ! 
Running gestures in terminal doesn't make program gestures working. But running gestures debug shows multiple rows. Unfortunately, I cannot check "Handlers for touchpads" because each time I try to scroll up the terminal / touch the screen (the device is a tablet), too many rows override the top of the terminal output. It's a pitty

Thank you, and by the way even if it does not work on my tablet, I really appreciate your app!

**Comment by natask** [comment]
you should close the script with control-c and then scroll up to see relevant output.
you can also run `gestures debug | grep Handlers` which only prints the Handlers.

I recommend doing a `git pull` beforehand. I have refined touchpad detection method.

**Comment by natask** [comment]
actually if you have multi row outputs that are generated when scrolling and touching the screen, the software detects your input methods.

The next thing I guess is `xdotool` isn't working.
can you try running `xdotool --help` to check if xdotool is installed? I assume the installation process didn't go smoothly.
